version: "3"
services:
  growth:
    image: dbandfield/growth
    ports:
      - "80:80"
    environment:
      GROWTH_DB_USER: growth
      GROWTH_DB_PASSWORD: xee8t6u3t
      RESET_DB_ON_START: "true"
    depends_on:
      - growth-db
  growth-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - "./setup-db.js:/docker-entrypoint-initdb.d/setup-db.js"
